# -*- coding: utf-8 -*-
"""05_Visualizingdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10zOUols1h6U7HH_y7yyjoUi3dc_oWuiy
"""

import pandas as pd

!pip install datasets

from datasets import load_dataset

data = load_dataset('lukebarousse/data_jobs')

df = data['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

Aus_Job = df[df.job_country == 'Australia']

aus_jobs = Aus_Job[Aus_Job.salary_year_avg.notna()]

aus_jobs.groupby('job_title_short')['salary_year_avg'].agg(['min','max','median','mean']).sort_values(by = 'median',ascending = False)

import matplotlib.pyplot as plt

x= [1,2,3,4]
y= [1,2,3,4]

plt.plot(x,y)
plt.show()

aus_jobs.job_posted_date.head()

aus_jobs['job_posted_month'] = df['job_posted_date'].dt.month

monthly_counts = aus_jobs.job_posted_month.value_counts()
monthly_counts= monthly_counts.sort_index()

monthly_counts

plt.plot(monthly_counts.index,monthly_counts)

job_counts = aus_jobs.job_title_short.value_counts().sort_values(ascending= True)

plt.barh(job_counts.index,job_counts)
plt.title("Postings by Job Post")
plt.xlabel("Count of Job Posting")
plt.ylabel("Skills")

job_counts.plot(kind = 'bar')

aus_jobs.plot(x= 'job_posted_date',y= 'salary_year_avg',kind = 'line')

aus_jobs.groupby('job_title_short')['salary_year_avg'].median().sort_values().plot(kind = 'barh')
plt.xlabel("Salary ($USD)")

