# -*- coding: utf-8 -*-
"""06_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNKvQyTnMzeXah0UbuvtLRWrbZS6DZ5s
"""

import pandas as pd

!pip install datasets

from datasets import load_dataset
data = load_dataset('lukebarousse/data_jobs')
df = data['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

Aus_Job = df[df.job_country == 'Australia']
aus_jobs = Aus_Job[Aus_Job.salary_year_avg.notna()]

Aus_Job = df[df.job_country == 'Australia']
aus_jobs = Aus_Job[Aus_Job.salary_year_avg.notna()]

median_Salary_year  = df['salary_year_avg'].median()
median_Salary_hourly  = df['salary_hour_avg'].median()

df_filled = df

df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_Salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_Salary_hourly)

df_filled.loc[:,'salary_year_avg':'salary_hour_avg']

df_unique = df_filled

df_unique = df_unique.drop_duplicates()

df_unique = df_unique.drop_duplicates(subset = ['job_title','company_name'] )

df_unique

df_salary_job_country = df.pivot_table(values = 'salary_year_avg',index = 'job_country',columns = 'job_title_short',aggfunc='median')

df_salary_job_country

top_countries = df['job_country'].value_counts().head(10).index

top10Countries = df_salary_job_country.loc[top_countries]

job_titles = ['Data Analyst','Data Engineer','Data Scientist']

df_job_country_salary = top10Countries[job_titles]

df_job_country_salary

df_job_country_salary.plot(kind = 'bar')

df_exploded = df.explode('job_skills')

df_exploded['job_skills'].value_counts().head(10).plot(kind='bar')

skillcounts = df_exploded.groupby(['job_title_short','job_skills']).size()

df_skills_count = skillcounts.reset_index(name = 'skill_count')
df_skills_count = df_skills_count.sort_values(by= 'skill_count',ascending =False)

job_title = 'Data Analyst'
top_skills = 10

df_skill_final = df_skills_count[df_skills_count['job_title_short']== job_title].head(top_skills)

df_skill_final.plot(kind = 'barh',x= 'job_skills',y = 'skill_count')

import matplotlib.pyplot as plt


fig,ax= plt.subplots(1,2)

df['job_title_short'].value_counts().plot(kind = 'bar',ax=ax[0])
df['job_schedule_type'].value_counts().head(5).plot(kind = 'bar',ax=ax[1])

fig.tight_layout()

df_exploded.head()

skills_stats = df_exploded.groupby('job_skills').agg(skill_count = ('job_skills','count'),median_salary=('salary_year_avg','median'))
skills_stats = skills_stats.sort_values(by= 'skill_count',ascending = False).head(10)

skills_stats.plot(kind = 'scatter',x='skill_count',y='median_salary')

for i,txt in enumerate(skills_stats.index):
  plt.text(skills_stats['skill_count'].iloc[i],skills_stats['median_salary'].iloc[i],txt)
  plt.tight_layout()

df_exploded